import React, { useState } from "react";
import { 
  Search, 
  Activity, 
  ShieldCheck, 
  Zap, 
  Globe, 
  AlertCircle, 
  CheckCircle2, 
  BarChart3, 
  ArrowRight,
  Loader2,
  ExternalLink,
  Info,
  Languages
} from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
import { GoogleGenAI } from "@google/genai";
import Markdown from "react-markdown";
import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

type Language = "en" | "pl";

const translations = {
  en: {
    title: "SiteHealth",
    dashboard: "Dashboard",
    history: "History",
    settings: "Settings",
    heroTitle: "Evaluate your website's health in seconds.",
    heroDesc: "Enter a URL to get a comprehensive audit of SEO, accessibility, and user experience powered by Gemini AI.",
    placeholder: "https://example.com",
    scan: "Scan",
    scanning: "Scanning...",
    errorTitle: "Scan Error",
    visit: "Visit",
    metaDesc: "Meta Description",
    h1Label: "H1 Headers",
    imagesLabel: "Images",
    h2Label: "H2 Headers",
    linksLabel: "Links",
    missingAlt: "missing alt",
    aiAudit: "AI Health Audit",
    aiModel: "Generated by Gemini 3 Flash",
    analysisComplete: "Analysis Complete",
    analyzing: "Analyzing content and metadata...",
    seoAudit: "SEO Audit",
    seoDesc: "Check meta tags, header structure, and keyword distribution automatically.",
    accessibility: "Accessibility",
    accDesc: "Identify missing alt tags, poor contrast, and structural issues for better inclusivity.",
    aiInsights: "AI Insights",
    aiDesc: "Get personalized recommendations on how to improve your site's conversion and UX.",
    privacy: "Privacy",
    terms: "Terms",
    api: "API",
    copyright: "© 2024 SiteHealth. Built with Gemini AI.",
    aiPrompt: (url: string, metadata: any, content: string) => `Analyze the following website metadata and content snippet for "Site Health". 
        Provide a professional audit report in Markdown format.
        Include sections for:
        1. SEO Analysis (Title, Description, Headers)
        2. Accessibility (Images, Structure)
        3. Content Quality
        4. UX Recommendations
        5. Overall Health Score (0-100)
        
        Website URL: ${url}
        Metadata: ${JSON.stringify(metadata, null, 2)}
        Content Snippet: ${content}`
  },
  pl: {
    title: "SiteHealth",
    dashboard: "Panel",
    history: "Historia",
    settings: "Ustawienia",
    heroTitle: "Oceń stan swojej strony w kilka sekund.",
    heroDesc: "Wprowadź adres URL, aby otrzymać kompleksowy audyt SEO, dostępności i doświadczenia użytkownika wspierany przez Gemini AI.",
    placeholder: "https://przyklad.pl",
    scan: "Skanuj",
    scanning: "Skanowanie...",
    errorTitle: "Błąd skanowania",
    visit: "Odwiedź",
    metaDesc: "Opis Meta",
    h1Label: "Nagłówki H1",
    imagesLabel: "Obrazy",
    h2Label: "Nagłówki H2",
    linksLabel: "Linki",
    missingAlt: "brak alt",
    aiAudit: "Audyt Zdrowia AI",
    aiModel: "Wygenerowano przez Gemini 3 Flash",
    analysisComplete: "Analiza zakończona",
    analyzing: "Analizowanie treści i metadanych...",
    seoAudit: "Audyt SEO",
    seoDesc: "Automatycznie sprawdzaj tagi meta, strukturę nagłówków i rozkład słów kluczowych.",
    accessibility: "Dostępność",
    accDesc: "Zidentyfikuj brakujące tagi alt, słaby kontrast i problemy strukturalne dla lepszej inkluzywności.",
    aiInsights: "Wnioski AI",
    aiDesc: "Otrzymuj spersonalizowane rekomendacje dotyczące poprawy konwersji i UX Twojej witryny.",
    privacy: "Prywatność",
    terms: "Warunki",
    api: "API",
    copyright: "© 2024 SiteHealth. Zbudowano z Gemini AI.",
    aiPrompt: (url: string, metadata: any, content: string) => `Przeanalizuj poniższe metadane strony internetowej i fragment treści pod kątem "Zdrowia Strony" (Site Health).
        Przygotuj profesjonalny raport z audytu w formacie Markdown w języku POLSKIM.
        Uwzględnij sekcje:
        1. Analiza SEO (Tytuł, Opis, Nagłówki)
        2. Dostępność (Obrazy, Struktura)
        3. Jakość treści
        4. Rekomendacje UX
        5. Ogólny wynik zdrowia (0-100)
        
        URL strony: ${url}
        Metadane: ${JSON.stringify(metadata, null, 2)}
        Fragment treści: ${content}`
  }
};

interface ScanMetadata {
  title: string;
  description: string;
  h1Count: number;
  h2Count: number;
  imageCount: number;
  imagesWithoutAlt: number;
  linksCount: number;
  canonical: string;
  ogTitle?: string;
  ogDescription?: string;
  favicon?: string;
}

interface ScanResult {
  url: string;
  metadata: ScanMetadata;
  contentSnippet: string;
}

export default function App() {
  const [lang, setLang] = useState<Language>("pl");
  const t = translations[lang];

  const [url, setUrl] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<ScanResult | null>(null);
  const [aiReport, setAiReport] = useState<string | null>(null);

  const toggleLang = () => {
    setLang(prev => prev === "en" ? "pl" : "en");
  };

  const handleScan = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!url) return;

    setIsLoading(true);
    setError(null);
    setResult(null);
    setAiReport(null);

    try {
      const response = await fetch("/api/scan", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url }),
      });

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || t.errorTitle);
      }

      const data: ScanResult = await response.json();
      setResult(data);
      
      // Generate AI Report
      await generateAiReport(data);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setIsLoading(false);
    }
  };

  const generateAiReport = async (scanData: ScanResult) => {
    try {
      const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
      const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: t.aiPrompt(scanData.url, scanData.metadata, scanData.contentSnippet),
      });

      setAiReport(response.text || "No report generated.");
    } catch (err) {
      console.error("AI Report Error:", err);
      setAiReport(lang === "pl" ? "Nie udało się wygenerować raportu AI." : "Failed to generate AI report.");
    }
  };

  return (
    <div className="min-h-screen bg-[#F5F5F5] text-[#1A1A1A] font-sans selection:bg-emerald-100">
      {/* Header */}
      <header className="bg-white border-b border-black/5 sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-emerald-600 rounded-lg flex items-center justify-center text-white">
              <Activity size={20} />
            </div>
            <h1 className="text-xl font-bold tracking-tight">{t.title}</h1>
          </div>
          
          <div className="flex items-center gap-6">
            <nav className="hidden md:flex items-center gap-6 text-sm font-medium text-black/60">
              <a href="#" className="hover:text-black transition-colors">{t.dashboard}</a>
              <a href="#" className="hover:text-black transition-colors">{t.history}</a>
              <a href="#" className="hover:text-black transition-colors">{t.settings}</a>
            </nav>
            
            <button 
              onClick={toggleLang}
              className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-black/5 hover:bg-black/10 transition-colors text-xs font-bold uppercase tracking-wider"
            >
              <Languages size={14} />
              {lang}
            </button>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 py-8">
        {/* Hero / Search Section */}
        <section className="mb-12 text-center max-w-2xl mx-auto">
          <motion.h2 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-4xl font-bold mb-4 tracking-tight"
          >
            {t.heroTitle}
          </motion.h2>
          <motion.p 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="text-black/60 mb-8"
          >
            {t.heroDesc}
          </motion.p>

          <form onSubmit={handleScan} className="relative group">
            <div className="absolute inset-y-0 left-4 flex items-center pointer-events-none text-black/40 group-focus-within:text-emerald-600 transition-colors">
              <Search size={20} />
            </div>
            <input
              type="text"
              placeholder={t.placeholder}
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              className="w-full bg-white border border-black/10 rounded-2xl py-4 pl-12 pr-32 focus:outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500 transition-all shadow-sm"
            />
            <button
              type="submit"
              disabled={isLoading}
              className="absolute right-2 top-2 bottom-2 bg-emerald-600 hover:bg-emerald-700 text-white px-6 rounded-xl font-medium transition-colors flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed min-w-[100px] justify-center"
            >
              {isLoading ? (
                <Loader2 size={18} className="animate-spin" />
              ) : (
                <>
                  {t.scan} <ArrowRight size={18} />
                </>
              )}
            </button>
          </form>

          {error && (
            <motion.div 
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              className="mt-4 p-4 bg-red-50 border border-red-100 text-red-600 rounded-xl flex items-center gap-3 text-sm"
            >
              <AlertCircle size={18} />
              {error}
            </motion.div>
          )}
        </section>

        <AnimatePresence mode="wait">
          {result && (
            <motion.div
              key="results"
              initial={{ opacity: 0, y: 40 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: 40 }}
              className="grid grid-cols-1 lg:grid-cols-3 gap-8"
            >
              {/* Left Column: Summary & Metadata */}
              <div className="lg:col-span-1 space-y-6">
                <div className="bg-white rounded-2xl p-6 border border-black/5 shadow-sm">
                  <div className="flex items-center gap-3 mb-6">
                    {result.metadata.favicon ? (
                      <img src={result.metadata.favicon} alt="" className="w-6 h-6 rounded" />
                    ) : (
                      <Globe className="text-black/40" size={24} />
                    )}
                    <h3 className="font-bold truncate" title={result.metadata.title}>
                      {result.metadata.title}
                    </h3>
                  </div>
                  
                  <div className="space-y-4">
                    <div className="flex justify-between items-center text-sm">
                      <span className="text-black/40">URL</span>
                      <a href={result.url} target="_blank" rel="noopener noreferrer" className="text-emerald-600 hover:underline flex items-center gap-1">
                        {t.visit} <ExternalLink size={12} />
                      </a>
                    </div>
                    <div className="border-t border-black/5 pt-4">
                      <p className="text-xs font-semibold text-black/40 uppercase tracking-wider mb-2">{t.metaDesc}</p>
                      <p className="text-sm leading-relaxed text-black/70 italic">
                        "{result.metadata.description}"
                      </p>
                    </div>
                  </div>
                </div>

                {/* Stats Grid */}
                <div className="grid grid-cols-2 gap-4">
                  <StatCard 
                    icon={<BarChart3 size={18} />} 
                    label={t.h1Label} 
                    value={result.metadata.h1Count} 
                    status={result.metadata.h1Count === 1 ? "success" : "warning"}
                  />
                  <StatCard 
                    icon={<ShieldCheck size={18} />} 
                    label={t.imagesLabel} 
                    value={result.metadata.imageCount} 
                    subValue={`${result.metadata.imagesWithoutAlt} ${t.missingAlt}`}
                    status={result.metadata.imagesWithoutAlt === 0 ? "success" : "error"}
                  />
                  <StatCard 
                    icon={<Zap size={18} />} 
                    label={t.h2Label} 
                    value={result.metadata.h2Count} 
                  />
                  <StatCard 
                    icon={<Globe size={18} />} 
                    label={t.linksLabel} 
                    value={result.metadata.linksCount} 
                  />
                </div>
              </div>

              {/* Right Column: AI Report */}
              <div className="lg:col-span-2">
                <div className="bg-white rounded-2xl border border-black/5 shadow-sm overflow-hidden h-full flex flex-col">
                  <div className="p-6 border-b border-black/5 flex items-center justify-between bg-emerald-50/30">
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 bg-emerald-100 rounded-xl flex items-center justify-center text-emerald-700">
                        <Activity size={20} />
                      </div>
                      <div>
                        <h3 className="font-bold">{t.aiAudit}</h3>
                        <p className="text-xs text-black/40">{t.aiModel}</p>
                      </div>
                    </div>
                    {aiReport && (
                      <div className="flex items-center gap-2 text-xs font-medium bg-emerald-100 text-emerald-700 px-3 py-1 rounded-full">
                        <CheckCircle2 size={14} /> {t.analysisComplete}
                      </div>
                    )}
                  </div>
                  
                  <div className="p-8 flex-grow overflow-auto prose prose-emerald max-w-none">
                    {!aiReport ? (
                      <div className="flex flex-col items-center justify-center h-64 text-black/40 space-y-4">
                        <Loader2 size={32} className="animate-spin text-emerald-600" />
                        <p className="animate-pulse">{t.analyzing}</p>
                      </div>
                    ) : (
                      <div className="markdown-body">
                        <Markdown>{aiReport}</Markdown>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Empty State */}
        {!result && !isLoading && (
          <div className="mt-20 grid grid-cols-1 md:grid-cols-3 gap-8">
            <FeatureCard 
              icon={<Search className="text-blue-500" />}
              title={t.seoAudit}
              description={t.seoDesc}
            />
            <FeatureCard 
              icon={<ShieldCheck className="text-emerald-500" />}
              title={t.accessibility}
              description={t.accDesc}
            />
            <FeatureCard 
              icon={<Zap className="text-amber-500" />}
              title={t.aiInsights}
              description={t.aiDesc}
            />
          </div>
        )}
      </main>

      <footer className="mt-20 border-t border-black/5 py-12 bg-white">
        <div className="max-w-7xl mx-auto px-4 flex flex-col md:flex-row justify-between items-center gap-6">
          <div className="flex items-center gap-2 opacity-50">
            <Activity size={18} />
            <span className="font-bold text-sm">{t.title} Scanner</span>
          </div>
          <p className="text-sm text-black/40">{t.copyright}</p>
          <div className="flex gap-6 text-sm text-black/40 font-medium">
            <a href="#" className="hover:text-black">{t.privacy}</a>
            <a href="#" className="hover:text-black">{t.terms}</a>
            <a href="#" className="hover:text-black">{t.api}</a>
          </div>
        </div>
      </footer>
    </div>
  );
}

function StatCard({ icon, label, value, subValue, status }: { 
  icon: React.ReactNode, 
  label: string, 
  value: string | number,
  subValue?: string,
  status?: "success" | "warning" | "error"
}) {
  return (
    <div className="bg-white p-4 rounded-2xl border border-black/5 shadow-sm">
      <div className={cn(
        "w-8 h-8 rounded-lg flex items-center justify-center mb-3",
        status === "success" ? "bg-emerald-50 text-emerald-600" :
        status === "warning" ? "bg-amber-50 text-amber-600" :
        status === "error" ? "bg-red-50 text-red-600" :
        "bg-black/5 text-black/40"
      )}>
        {icon}
      </div>
      <p className="text-xs font-medium text-black/40 mb-1">{label}</p>
      <p className="text-2xl font-bold tracking-tight">{value}</p>
      {subValue && <p className="text-[10px] mt-1 text-black/40 font-medium">{subValue}</p>}
    </div>
  );
}

function FeatureCard({ icon, title, description }: { icon: React.ReactNode, title: string, description: string }) {
  return (
    <div className="bg-white p-8 rounded-3xl border border-black/5 shadow-sm hover:shadow-md transition-shadow">
      <div className="w-12 h-12 bg-black/5 rounded-2xl flex items-center justify-center mb-6">
        {icon}
      </div>
      <h3 className="text-lg font-bold mb-2">{title}</h3>
      <p className="text-sm text-black/60 leading-relaxed">{description}</p>
    </div>
  );
}
